language: node_js
node_js:
  - "0.10"
  - "0.12"

notifications:
  email:
    - "johnny.estilles@agentia.asia"

addons:
  code_climate:
    repo_token: f1f470708480edeb0868ea4755f603374df7c1122fdff3dda21be12d24ec4a31

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter

after_script:
  - gulp coverage
  - codeclimate < ./coverage/lcov.info
